/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.uniensinojavaswing.murilo.swing.gerador.de.senhas.murilo.nata.nogueira.visao;

import Controle.SenhaControle;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import javax.swing.JOptionPane;

/**
 *
 * @author muril
 */
public class visao extends javax.swing.JFrame {
    SenhaControle controle = new SenhaControle();
    int tamanho = 0;
    /**
     * Creates new form visao
     */
    public visao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkMaiuscula = new javax.swing.JCheckBox();
        checkEspecial = new javax.swing.JCheckBox();
        checkMinuscula = new javax.swing.JCheckBox();
        checkNumero = new javax.swing.JCheckBox();
        btnGeraSenha = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        textTamanho = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelSenha = new javax.swing.JLabel();
        btnCopiaSenha = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        checkMaiuscula.setText("Maiusculas");

        checkEspecial.setText("Especiais");

        checkMinuscula.setText("Minusculas");

        checkNumero.setText("Numeros");

        btnGeraSenha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnGeraSenha.setText("GERAR SENHA");
        btnGeraSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeraSenhaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Senha: ");

        jLabel2.setText("Tamanho da senha");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("GERADOR DE SENHAS");

        btnCopiaSenha.setText("Copiar senha");
        btnCopiaSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCopiaSenhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textTamanho)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(checkMaiuscula, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(checkMinuscula, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(checkNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(checkEspecial, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelSenha))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(jLabel3)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCopiaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(btnGeraSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkMaiuscula)
                    .addComponent(checkMinuscula)
                    .addComponent(checkNumero)
                    .addComponent(checkEspecial))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGeraSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(labelSenha))
                .addGap(7, 7, 7)
                .addComponent(btnCopiaSenha))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGeraSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeraSenhaActionPerformed
        if(verificaTamanho())
        {
            verificaChecks();
        }
        
    }//GEN-LAST:event_btnGeraSenhaActionPerformed

    private void btnCopiaSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCopiaSenhaActionPerformed
        if(!labelSenha.getText().isBlank())
        {
            String senha = labelSenha.getText();
            StringSelection selection = new StringSelection(senha);

            Clipboard clip = Toolkit.getDefaultToolkit().getSystemClipboard();
            clip.setContents(selection, null);

            JOptionPane.showMessageDialog(this, "Senha copiada!");
        }
    }//GEN-LAST:event_btnCopiaSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    private void verificaChecks(){
        boolean maiusuclas = checkMaiuscula.isSelected();
        boolean minusculas = checkMinuscula.isSelected();
        boolean numeros = checkNumero.isSelected();
        boolean especiais = checkEspecial.isSelected();
        
        if(maiusuclas || minusculas || numeros || especiais) {
            labelSenha.setText(controle.gerarSenha(maiusuclas, minusculas, numeros, especiais, tamanho));
        } else {
            JOptionPane.showMessageDialog(this, "Não pode-se gerar senha sem nenhum item selecionado");
        }
        
    }
    
    private boolean verificaTamanho(){
        try{
            tamanho = Integer.parseInt(textTamanho.getText());
            if(tamanho <= 0) 
            {
                JOptionPane.showMessageDialog(this, "Tamanho inválido, coloque números inteiros positivos");
                return false;
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Formato inválido, coloque números inteiros positivos");
        }
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCopiaSenha;
    private javax.swing.JButton btnGeraSenha;
    private javax.swing.JCheckBox checkEspecial;
    private javax.swing.JCheckBox checkMaiuscula;
    private javax.swing.JCheckBox checkMinuscula;
    private javax.swing.JCheckBox checkNumero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JTextField textTamanho;
    // End of variables declaration//GEN-END:variables
}
